// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using meetupsApi.Models;

namespace meetupsApi.Migrations
{
    [DbContext(typeof(MeetupsApiContext))]
    [Migration("20181123142951_addConnpassDataColumn")]
    partial class addConnpassDataColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("meetupsApi.Domain.Entity.ConnpassEventDataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Lat");

                    b.Property<double>("Lon");

                    b.Property<int>("accepted");

                    b.Property<string>("address");

                    b.Property<string>("catchMesagge");

                    b.Property<string>("description");

                    b.Property<DateTime>("ended_at");

                    b.Property<string>("event_type");

                    b.Property<string>("event_url");

                    b.Property<string>("hash_tag");

                    b.Property<int>("limit");

                    b.Property<int>("owned_id");

                    b.Property<string>("owned_nickname");

                    b.Property<string>("owner_display_name");

                    b.Property<DateTime>("started_at");

                    b.Property<string>("title");

                    b.Property<DateTime>("updated_at");

                    b.Property<int>("waiting");

                    b.HasKey("Id");

                    b.ToTable("ConnpassEventDataEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
