// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using meetupsApi.Models;

namespace meetupsApi.Migrations
{
    [DbContext(typeof(MeetupsApiContext))]
    [Migration("20181029084916_CreateEventTable")]
    partial class CreateEventTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("meetupsApi.JsonEntity.Event", b =>
                {
                    b.Property<int>("event_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("_catch");

                    b.Property<int>("accepted");

                    b.Property<string>("address");

                    b.Property<string>("description");

                    b.Property<DateTime>("ended_at");

                    b.Property<string>("event_type");

                    b.Property<string>("event_url");

                    b.Property<string>("hash_tag");

                    b.Property<string>("lat");

                    b.Property<int>("limit");

                    b.Property<string>("lon");

                    b.Property<string>("owner_display_name");

                    b.Property<int>("owner_id");

                    b.Property<string>("owner_nickname");

                    b.Property<string>("place");

                    b.Property<int?>("seriesid");

                    b.Property<DateTime>("started_at");

                    b.Property<string>("title");

                    b.Property<DateTime>("updated_at");

                    b.Property<int>("waiting");

                    b.HasKey("event_id");

                    b.HasIndex("seriesid");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("meetupsApi.JsonEntity.Series", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("title");

                    b.Property<string>("url");

                    b.HasKey("id");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("meetupsApi.JsonEntity.Event", b =>
                {
                    b.HasOne("meetupsApi.JsonEntity.Series", "series")
                        .WithMany()
                        .HasForeignKey("seriesid");
                });
#pragma warning restore 612, 618
        }
    }
}
